### ISSUE TITLE
配置为灰色，不能在页面修改。 

### ISSUE THREAD

**Issue by nondevops** [canyuegongzi/simple-file-center-web#4]
![image](https://user-images.githubusercontent.com/12181410/136907843-7430b6a7-8b2a-4edb-8a27-f1b939e4b292.png)

**Comment by canyuegongzi** [comment]
这个是云存储的配置信息，只有管理员能修改，之前那个跳转的问题，那是单点登录

**Comment by nondevops** [comment]
如果是个人使用，单点登录是否可以去掉呢 @canyuegongzi
